# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
print("Numpy version:", np.__version__)
np.show_config()


Numpy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4347739648
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a51i_mbs7m/croot/numpy_and_numpy_base_1708638620867/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug-prefix-map=/opt/anac

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [5]:
a = np.random.random((2, 3, 5))



### 4. Print a.


In [7]:
print(a)

[[[0.74411204 0.44608578 0.79935551 0.93920166 0.08225815]
  [0.05591466 0.33745752 0.18403089 0.49378073 0.2628353 ]
  [0.71118781 0.75518452 0.09079292 0.89716115 0.60098244]]

 [[0.96446095 0.53387001 0.91148732 0.22958459 0.79440875]
  [0.83345698 0.83330382 0.4534126  0.24311432 0.24286439]
  [0.66583925 0.7309965  0.94046122 0.59278599 0.06729198]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [9]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [11]:
print(a.size == b.size)


True



### 8. Are you able to add a and b? Why or why not?


In [ ]:
a + b  # No se pueden sumar porque tienen formas distintas

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [15]:
c = np.transpose(b, (1, 2, 0))
print(c.shape)

(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [17]:
d = a + c # Funciona porque tienen la misma forma
print(d)


[[[1.74411204 1.44608578 1.79935551 1.93920166 1.08225815]
  [1.05591466 1.33745752 1.18403089 1.49378073 1.2628353 ]
  [1.71118781 1.75518452 1.09079292 1.89716115 1.60098244]]

 [[1.96446095 1.53387001 1.91148732 1.22958459 1.79440875]
  [1.83345698 1.83330382 1.4534126  1.24311432 1.24286439]
  [1.66583925 1.7309965  1.94046122 1.59278599 1.06729198]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a)
print(d)
# La diferencia es la suma de 1 para todos los valores en d.

[[[0.74411204 0.44608578 0.79935551 0.93920166 0.08225815]
  [0.05591466 0.33745752 0.18403089 0.49378073 0.2628353 ]
  [0.71118781 0.75518452 0.09079292 0.89716115 0.60098244]]

 [[0.96446095 0.53387001 0.91148732 0.22958459 0.79440875]
  [0.83345698 0.83330382 0.4534126  0.24311432 0.24286439]
  [0.66583925 0.7309965  0.94046122 0.59278599 0.06729198]]]
[[[1.74411204 1.44608578 1.79935551 1.93920166 1.08225815]
  [1.05591466 1.33745752 1.18403089 1.49378073 1.2628353 ]
  [1.71118781 1.75518452 1.09079292 1.89716115 1.60098244]]

 [[1.96446095 1.53387001 1.91148732 1.22958459 1.79440875]
  [1.83345698 1.83330382 1.4534126  1.24311432 1.24286439]
  [1.66583925 1.7309965  1.94046122 1.59278599 1.06729198]]]



### 12. Multiply a and c. Assign the result to e.


In [19]:
e = a * c
print(e)

[[[0.74411204 0.44608578 0.79935551 0.93920166 0.08225815]
  [0.05591466 0.33745752 0.18403089 0.49378073 0.2628353 ]
  [0.71118781 0.75518452 0.09079292 0.89716115 0.60098244]]

 [[0.96446095 0.53387001 0.91148732 0.22958459 0.79440875]
  [0.83345698 0.83330382 0.4534126  0.24311432 0.24286439]
  [0.66583925 0.7309965  0.94046122 0.59278599 0.06729198]]]




### 13. Does e equal to a? Why or why not?


In [ ]:
print(np.array_equal(e, a))
 # son iguales porque multiplicar cualquier número por 1 no cambia su valor, y c solo contiene unos.


True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [25]:
d_max = np.max(d)
print(d_max)
d_min = np.min(d)
print(d_min)
d_mean = np.mean(d)
print(d_mean)

1.9644609518788632
1.0559146556348682
1.547922658548651



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [30]:
f = np.empty(d.shape)
print(f)

[[[0.74411204 0.44608578 0.79935551 0.93920166 0.08225815]
  [0.05591466 0.33745752 0.18403089 0.49378073 0.2628353 ]
  [0.71118781 0.75518452 0.09079292 0.89716115 0.60098244]]

 [[0.96446095 0.53387001 0.91148732 0.22958459 0.79440875]
  [0.83345698 0.83330382 0.4534126  0.24311432 0.24286439]
  [0.66583925 0.7309965  0.94046122 0.59278599 0.06729198]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [34]:


for i in range(d.shape[0]):        
    for j in range(d.shape[1]):    
        for k in range(d.shape[2]): 
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = 75
            else:
                f[i, j, k] = 100







### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [33]:
print(d)
print(f)

[[[1.74411204 1.44608578 1.79935551 1.93920166 1.08225815]
  [1.05591466 1.33745752 1.18403089 1.49378073 1.2628353 ]
  [1.71118781 1.75518452 1.09079292 1.89716115 1.60098244]]

 [[1.96446095 1.53387001 1.91148732 1.22958459 1.79440875]
  [1.83345698 1.83330382 1.4534126  1.24311432 1.24286439]
  [1.66583925 1.7309965  1.94046122 1.59278599 1.06729198]]]
[[[ 75.  25.  75.  75.  25.]
  [  0.  25.  25.  25.  25.]
  [ 75.  75.  25.  75.  75.]]

 [[100.  25.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  75.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]